/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.jpl7.Query;
import java.util.*;

/**
 *
 * @author rzumb
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Generar Kakuro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(41);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 504));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n=9;
        String [][] tablero= new String[n][n];
        tablero=this.matrizProlog();
        this.mostrarMatriz(tablero, n);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
           
           
            
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
        
       
    
    }
        public void mostrarMatriz(String matriz[][], int n){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.isCellEditable(0, 0);
        model.setRowCount(n);
        model.setColumnCount(n);
        
            for(int i=0; i<n; i++){
                for(int j=0; j<n; j++){
                    jTable1.setValueAt(matriz[i][j], i, j);

                }

            }
        }
        
        public String[][] matrizProlog(){
            String t1= "consult('board.pl')";
            Query q1= new Query(t1);
            System.out.println(t1+""+(q1.hasSolution()? "satisfactoria":"insatisfactoria"));

            String t2="tablero(Tablero)";
            Query q2 = new Query(t2);

            String accion = q2.oneSolution().get("Tablero").toString();
            System.out.println(accion);
            String cadena = accion;
            List<String> fila = new ArrayList <String>();
            List<String> fila_completa = new ArrayList <String>();
            StringTokenizer st = new StringTokenizer(cadena, "[,\']");
            while(st.hasMoreTokens()){
                
                
                fila.add(st.nextToken());
                
               
            }
            Iterator it = fila.iterator();
            int i=0;
            while(it.hasNext()){
                if (it.next().equals(" ")){
                    it.remove();
                }
                
                i++;
            }
                
            
            for(i=0; i< fila.size();i++){
            
                if(fila.get(i).charAt(0) == '('){
                    fila_completa.add(fila.get(i).concat(",").concat(fila.get(i+1)));
                    i++;
                
                }
                else
                    fila_completa.add(fila.get(i).concat(" "));
            
            
            }
            String [][] matriz= new String [9][9];
            int h=0;
            int j=0;
            for (i=0; i< fila_completa.size(); i++){
                if (j<9 && fila_completa.get(i).charAt(1) == '_'){
                    matriz [h][j] = " ";
                    j++;
                }
                else if (j<9 && fila_completa.get(i).charAt(1) != '_'){
                    matriz [h][j] = fila_completa.get(i);
                    j++;
                }
                else if (j>=9 && fila_completa.get(i).charAt(1) == '_'){
                    matriz [h][j] = " ";
                    j++;
                }
                else{
                    j=0;
                    h++;
                    matriz[h][j] = fila_completa.get(i);
                    j++;
                    
                }
            }
            return matriz;
        }
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
